C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\cathedral_montreal_0.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\cathedral_montreal_1.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\cathedral_montreal_2.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\cathedral_montreal_3.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\cathedral_montreal_4.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\cathedral_montreal_5.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
C:\dev_painterly_render_u_saliency\x64\Debug\SaliencyPainterlyRendering.exe \render\src\market_montreal.jpg \render\deployment\deploy_s25_d7_g5_b5_N1_ps6_rTwopass_sItti_mAttach_gs1_copy.json
