dir ..\src\getty*/b > getty.lst
dir ..\src\under_sea*/b > under_sea.lst
dir ..\src\source*/b > source.lst
dir ..\src\sea_wave*/b > seawave.lst
dir ..\src\eos*/b > eos.lst
dir ..\src\cathedral*/b > cathedral.lst
dir ..\src\1534*/b > 1534.lst
dir ..\src\long*/b > long.lst
dir ..\src\IMGP*/b > imgp.lst
dir ..\src\photo*/b > photo.lst