C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SPregraph_s10_d7_g10_b10_N1_ps6_gs1_ts200_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SItti_s10_d7_g10_b10_N1_ps6_gs1_ts200_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SResidual_s10_d7_g10_b10_N1_ps6_gs1_ts200_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SBlackandwhite_s10_d7_g10_b10_N1_ps6_gs1_ts200_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SFine_grained_s10_d7_g10_b10_N1_ps6_gs1_ts200_copy.json
