C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SPregraph_s15_d7_g10_b5_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SItti_s15_d7_g10_b5_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SResidual_s15_d7_g10_b5_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SBlackandwhite_s15_d7_g10_b5_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SFine_grained_s15_d7_g10_b5_N1_ps6_gs1_ts230_copy.json
