C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SPregraph_s25_d5_g10_b10_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SItti_s25_d5_g10_b10_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SResidual_s25_d5_g10_b10_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SBlackandwhite_s25_d5_g10_b10_N1_ps6_gs1_ts230_copy.json
C:\dev_painterly_rendering_u_saliency\SaliencyPainterlyRendering\x64\Debug\SaliencyPainterlyRendering.exe %1 \render\deployment\SFine_grained_s25_d5_g10_b10_N1_ps6_gs1_ts230_copy.json
